# -*- coding: utf-8 -*-
"""Python lab cycle 1Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QnsaJhoLWAsb67ve860V8XIa-GkiQprY
"""

#Develop a program to perform the following task:

#a. Define a function to check whether a number is happy or not.

#b. Define a function to print all happy numbers within a range.

#c. Define a function to print first N happy numbers.

#A happy number is a number defined by the following process:

#• Starting with any positive integer, replace the number with the 

#sum of the squares of its digits.

#• Repeat the process until the number equals 1 (where it will 

#stay), or it loops endlessly in a cycle which does not include 1.

#• Those numbers for which this process ends in 1 are happy.


def print_in_a_range(l,u):
  for i in range(l,u+1):
    isHappy = check_happy(i)
    if isHappy:
      print(i,end=",")


def print_upto_n(n):
   for i in range(1,n+1):
     isHappy = check_happy(i)
     if isHappy:
       print(i, end=",")


def check_happy(num):
  happy_sum =0
  numcopy= num
  is_happy=False
  for i in range(0,101):
    while numcopy>0:
      remainder = numcopy % 10
      numcopy = numcopy //10
      happy_sum = happy_sum + remainder**2
    if(happy_sum == 1):
      is_happy=True
      break
    else:
      numcopy = happy_sum
      happy_sum = 0
  return is_happy
num = int(input("Enter the number : "))
result = check_happy(num)
if result==True:
  print(num,"is happy")
else:
  print(num,"is sad")



lower_range = int(input("Enter the lower limits : "))
upper_range = int(input("Enter the upper range : "))
print_in_a_range(lower_range,upper_range)

limit = int(input("Enter the numbers upto which you want to print : "))
print_upto_n(limit)
