# -*- coding: utf-8 -*-
"""Python lab cycle1Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WS95aE0K_yuOHaQyZGZf_H9lxIfvOKjX
"""

#Develop a program to read the three sides of two triangles and 

#calculate the area of both. Define a function to read the three sides 

#  call it

# Also, define a function to calculate the area. Print the total

#area enclosed by both triangles and each triangle's contribution (%) 

#towards it.

def get_side():
  a = int (input("enter the first side of the triangle"))
  b = int (input("enter the second side of the triangle"))
  c = int (input("enter the third side of the triangle"))
  return a,b,c

def calc_area(a,b,c):
  s = ( a + b + c ) / 2
  area = (s*(s-a)*(s-b)*(s-c))**(1/2)
  return area

side1,side2,side3 = get_side()
Area = calc_area(side1,side2,side3)
print(Area)

side4,side5,side6 = get_side()
Area2 = calc_area(side4,side5,side6)
print(Area2)

Total_area= Area + Area2
print("Total area:",Total_area)

print("cont of triangle 1",(calc_area(side1,side2,side3)/Total_area)*100)
print("cont of traingle 2",(calc_area(side4,side5,side6)/Total_area)*100)
