# -*- coding: utf-8 -*-
"""Python Lab cycle 1Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rO04O2EMREvFA6poYcV8ZqF_mqAp9qyG
"""

#Develop a program to read a four-digit number and find its
#a. Sum of digits
#b. Reverse
#c. Difference between the product of digits at the odd position 
# find the product of digits at the even position.

num= int(input("Enter a number "))
d4 = num%10
num = num//10
d3 = num%10
num = num//10
d2 = num%10
num = num//10
d1 = num%10
num = num//10

sum= d4 + d3 + d2 + d1 
reverse = d4*1000 + d3*100 + d2*10 +d1
diference = (d1*d3)-(d2*d4)
print("The Sum is ",sum)
print("The reverse is ",reverse)
print("The diference is ",diference)